fix build failure against directory-1.2 (missing liftM)
[1 of 1] Compiling Codec.Archive.Zip ( Codec/Archive/Zip.hs, dist/build/Codec/Archive/Zip.o )

Codec/Archive/Zip.hs:207:19:
    Not in scope: `liftM'
    Perhaps you meant `liftA' (imported from Control.Applicative)

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>